/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCriteriaRouteImport } from './routes/_authenticated/criteria'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedPatternsRouteImport } from './routes/_authenticated/patterns'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people.index'
import { Route as AuthenticatedPeoplePersonIdRouteImport } from './routes/_authenticated/people.$personId'
import { Route as AuthenticatedPeopleNewRouteImport } from './routes/_authenticated/people.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCriteriaRoute = AuthenticatedCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatternsRoute = AuthenticatedPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeoplePersonIdRoute =
  AuthenticatedPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleNewRoute = AuthenticatedPeopleNewRouteImport.update({
  id: '/people/new',
  path: '/people/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/criteria': typeof AuthenticatedCriteriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/log': typeof AuthenticatedLogRoute
  '/patterns': typeof AuthenticatedPatternsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/people/new': typeof AuthenticatedPeopleNewRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/criteria': typeof AuthenticatedCriteriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/log': typeof AuthenticatedLogRoute
  '/patterns': typeof AuthenticatedPatternsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/people/new': typeof AuthenticatedPeopleNewRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/criteria': typeof AuthenticatedCriteriaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/patterns': typeof AuthenticatedPatternsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/_authenticated/people/new': typeof AuthenticatedPeopleNewRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/criteria'
    | '/dashboard'
    | '/log'
    | '/patterns'
    | '/settings'
    | '/people/$personId'
    | '/people/new'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/criteria'
    | '/dashboard'
    | '/log'
    | '/patterns'
    | '/settings'
    | '/people/$personId'
    | '/people/new'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/criteria'
    | '/_authenticated/dashboard'
    | '/_authenticated/log'
    | '/_authenticated/patterns'
    | '/_authenticated/settings'
    | '/_authenticated/people/$personId'
    | '/_authenticated/people/new'
    | '/_authenticated/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/criteria': {
      id: '/_authenticated/criteria'
      path: '/criteria'
      fullPath: '/criteria'
      preLoaderRoute: typeof AuthenticatedCriteriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patterns': {
      id: '/_authenticated/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof AuthenticatedPatternsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/$personId': {
      id: '/_authenticated/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/new': {
      id: '/_authenticated/people/new'
      path: '/people/new'
      fullPath: '/people/new'
      preLoaderRoute: typeof AuthenticatedPeopleNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCriteriaRoute: typeof AuthenticatedCriteriaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedPatternsRoute: typeof AuthenticatedPatternsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPeoplePersonIdRoute: typeof AuthenticatedPeoplePersonIdRoute
  AuthenticatedPeopleNewRoute: typeof AuthenticatedPeopleNewRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCriteriaRoute: AuthenticatedCriteriaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedPatternsRoute: AuthenticatedPatternsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPeoplePersonIdRoute: AuthenticatedPeoplePersonIdRoute,
  AuthenticatedPeopleNewRoute: AuthenticatedPeopleNewRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
